# A sample configuration file for a generic custom GPT. This file contains metadata and settings for creating a GPT. For more information, see https://help.openai.com/en/articles/8554397-creating-a-gpt.

# Using the OpenAI's GPT Builder. See https://help.openai.com/en/articles/8770868-gpt-builder
# ToDo: Build out the GPT Builder with step-by-step prompts and responses.
gpt_builder:
  message: "Make a {job title} who helps {whom} {do what}."

gpt_config:
  # name: max 50 characters
  name: "Custom GPT Name"

  # image: Path to image file or "Use DALL-E" to create one
  image: "Use DALL-E"

  # description: max 300 characters
  description: "A brief description of the GPT's purpose and functionality."

  # instructions: Provide detailed instructions on how the GPT should behave, its functionalities, and any particular behaviors to avoid.
  instructions:
    base_context: "Primary instructions for the GPT's behavior."
    process: "Outline step-by-step how the GPT should iteratively refine its behavior and parameters based on user input."
    refinements: "How should GPT respond to user changes after initial setup?"
    prohibitions: "List any actions or responses that the GPT should avoid."
    unknowns: "Describe how the GPT should handle questions or requests outside its knowledge base."

  # conversation_starters: Examples of prompts for the user to start the conversation. Max 12; only first 4 shown in UI
  conversation_starters:
    - "Hello! How can I assist you today?"
    - "What questions do you have about our services?"
    - "Feel free to ask me anything!"
    - "Tell me about your project."

  # knowledge_files: List of knowledge files to upload to the the GPT. Max 20 files up to 512MB/2 million tokens (~20,000 words) each [https://help.openai.com/en/articles/8843948-knowledge-in-gpts] and [https://chatgpt.com/share/66e97b03-ae1c-800d-a784-5c1e767aef3a]
  knowledge_files:
    - path: "/path/to/file1.md"  # Best for long-form, structured content
    - path: "/path/to/file2.txt" # Best for short-form, unstructured content

  # capabilities: List of capabilities that the GPT can perform. Free accounts may not be able to use these capabilities. For more information, see .
  capabilities:
    web_browsing: true
    image_generation: false
    code_interpreter: true

  # actions: List of outside actions that the GPT can perform. For more information, see https://chatgpt.com/g/g-TYEliDU6A-actionsgpt.
  actions:
    action_1:
      - authentication:
        - description: "Authentication Description"
        - type: "None" # Enum options: None, API Key, OAuth
        schema: "What Action 1 does."
        privacy_policy_url: "Link to privacy policy for Action 1."

  share: "Only me" # Enum options: "Only me", "Anyone with the link", "GPT Store"
  category: "Programming" # Enum options: "Writing", "Productivity", "Research & Analysis", "Education", "Lifestyle", "Programming", "Other"